dfdasfas

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -26,10 +26,14 @@ jobs:
         uses: actions/checkout@v4
       - name: dist以外のファイルが存在しないかチェック
         run: |
-          line="abcde"
-          if ! echo "$line" | grep -q "dist/"
-          then
-              echo "Error: dist以外のディレクトリが存在します。($line)"
-              exit 1
-          fi
-
+          echo 1 > test.txt
+          git add .
+          git commit -m "test"
+          git status --porcelain | while read -r line
+          do
+              if ! echo "$line" | grep -q "dist/"
+              then
+                  echo "Error: dist以外のディレクトリが存在します。($line)"
+                  exit 1
+              fi
+          done
