adfadsfasdfsa

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -24,13 +24,14 @@ jobs:
     steps:
       - name: コードのチェックアウト
         uses: actions/checkout@v4
-      - name: Node.js のセットアップ
-        uses: actions/setup-node@v4
-        with:
-            node-version: 14.21.3
-            cache: 'npm'
-
-      - name: プロジェクトをビルド
+      - name: dist以外のファイルが存在しないかチェック
         run: |
-          echo "OK!"
+          git status --porcelain | while read -r line
+          do
+              if ! echo "$line" | grep -q "dist/"
+              then
+                  echo "Error: dist以外のディレクトリが存在します。($line)"
+                  exit 1
+              fi
+          done
 
